import { autoUpdater } from "electron-updater";
import type { BrowserWindow } from "electron";
import type { UpdateStatus } from "@acme/contracts";
import { IPC_CHANNELS } from "./ipcChannels";

/**
 * Initialize auto-updater with generic provider pointing to R2.
 * electron-updater reads `publish` config from package.json's `build` field,
 * which is set to: { provider: "generic", url: "https://cdn.snug.video/releases/latest" }
 *
 * It expects these files on the server:
 *   - latest-mac.yml   (version metadata + checksums, generated by electron-builder)
 *   - Snug-<version>-mac.zip  (the actual update payload)
 */
export function initAutoUpdater(getWindow: () => BrowserWindow | null): void {
  // Download in the background; renderer shows a toast when ready to restart.
  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;

  const sendStatus = (status: UpdateStatus) => {
    const win = getWindow();
    if (!win?.webContents || win.isDestroyed()) return;
    win.webContents.send(IPC_CHANNELS.appUpdateStatus, status);
  };

  autoUpdater.on("checking-for-update", () => {
    sendStatus({ state: "checking" });
  });

  autoUpdater.on("update-available", (info) => {
    let releaseNotes: string | null = null;
    if (typeof info.releaseNotes === "string") releaseNotes = info.releaseNotes;
    else if (Array.isArray(info.releaseNotes))
      releaseNotes = info.releaseNotes.map((n) => String(n)).join("\n\n");

    sendStatus({
      state: "available",
      info: {
        version: info.version,
        releaseNotes
      }
    });
  });

  autoUpdater.on("update-not-available", () => {
    sendStatus({ state: "not-available" });
  });

  autoUpdater.on("download-progress", (progress) => {
    sendStatus({
      state: "downloading",
      progress: {
        percent: progress.percent,
        bytesPerSecond: progress.bytesPerSecond,
        transferred: progress.transferred,
        total: progress.total
      }
    });
  });

  autoUpdater.on("update-downloaded", (info) => {
    let releaseNotes: string | null = null;
    if (typeof info.releaseNotes === "string") releaseNotes = info.releaseNotes;
    else if (Array.isArray(info.releaseNotes))
      releaseNotes = info.releaseNotes.map((n) => String(n)).join("\n\n");

    sendStatus({
      state: "downloaded",
      info: {
        version: info.version,
        releaseNotes
      }
    });
  });

  autoUpdater.on("error", (err) => {
    sendStatus({ state: "error", message: err.message });
  });
}

/** Trigger a manual check for updates. */
export function checkForUpdate(): void {
  void autoUpdater.checkForUpdates();
}

/** Start downloading the available update. */
export function downloadUpdate(): void {
  void autoUpdater.downloadUpdate();
}

/** Quit the app and install the downloaded update. */
export function installUpdate(): void {
  autoUpdater.quitAndInstall();
}
